import { prisma } from "@/lib/prisma"
import { TryOnError } from "@/lib/tryon/gemini"
import { billingEnabled } from "./config"
import type { Plan } from "./plans"
import { addUsage, getEntitlement, getUsage, monthPeriod, type UsageField } from "./subscription"

/**
 * A cap or a missing plan. It is a TryOnError so the try-on routes already
 * turn it into a response with this status (402 no plan, 429 cap reached).
 */
export class PlanLimitError extends TryOnError {}

// Los avisos de sileo no parten el texto en líneas: cada mensaje debe caber en
// una pantalla de móvil (unos 45 caracteres)
const NEEDS_PLAN = "Necesitas un plan activo. Elígelo en Mi cuenta."

/** The user's plan, or null when billing is off. Throws when a plan is required and missing. */
async function planFor(userId: string): Promise<Plan | null> {
  const entitlement = await getEntitlement(userId)
  if (!entitlement.enforced) return null
  if (!entitlement.plan) throw new PlanLimitError(NEEDS_PLAN, 402)
  return entitlement.plan
}

/**
 * Ceiling on the looks generated by everyone in a month (TRYON_GLOBAL_MONTHLY_LIMIT).
 * The plan caps bound each customer; this bounds the total bill, however many
 * customers there are. Unset or 0 means no ceiling.
 */
export function globalMonthlyLimit(env = process.env): number | null {
  const value = Number(env.TRYON_GLOBAL_MONTHLY_LIMIT)
  return Number.isFinite(value) && value > 0 ? Math.floor(value) : null
}

async function checkGlobalAllowance(): Promise<void> {
  const limit = globalMonthlyLimit()
  if (limit === null) return
  const { _sum } = await prisma.usageMonth.aggregate({
    where: { period: monthPeriod() },
    _sum: { looks: true },
  })
  if ((_sum.looks ?? 0) >= limit) {
    console.error(`[billing] TRYON_GLOBAL_MONTHLY_LIMIT alcanzado (${limit} looks este mes)`)
    throw new PlanLimitError("Estamos al máximo de looks este mes. Vuelve pronto.", 503)
  }
}

/** Before generating a look. Returns the plan's daily cap, if plans apply. */
export async function checkLookAllowance(userId: string): Promise<{ dailyLimit?: number }> {
  const plan = await planFor(userId)
  if (!plan) return {}
  await checkGlobalAllowance()
  const usage = await getUsage(userId)
  if (usage.looks >= plan.limits.looksPerMonth) {
    throw new PlanLimitError("Llegaste al tope de looks de tu plan este mes.", 429)
  }
  return { dailyLimit: plan.limits.looksPerDay }
}

/** Before reviewing and storing a new base photo. */
export async function checkPhotoAllowance(userId: string): Promise<void> {
  const plan = await planFor(userId)
  if (!plan) return
  const usage = await getUsage(userId)
  if (usage.photoChanges >= plan.limits.photosPerMonth) {
    throw new PlanLimitError("Ya subiste las fotos base de tu plan este mes.", 429)
  }
}

/** Before adding a garment to the closet. */
export async function checkGarmentAllowance(userId: string): Promise<void> {
  const plan = await planFor(userId)
  if (!plan) return
  const [usage, closet] = await Promise.all([
    getUsage(userId),
    prisma.wardrobe.count({ where: { userId } }),
  ])
  if (usage.garments >= plan.limits.garmentsPerMonth) {
    throw new PlanLimitError("Ya cargaste las prendas de tu plan este mes.", 429)
  }
  if (closet >= plan.limits.closetMax) {
    throw new PlanLimitError("Tu closet llegó al máximo de tu plan.", 429)
  }
}

/** Counts a finished action against the month. A no-op while billing is off. */
export async function recordUsage(userId: string, field: UsageField): Promise<void> {
  if (!billingEnabled()) return
  await addUsage(userId, field)
}
